### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by martab0** [LeBerek/Markdown_vistula#3]
Świetnie! Jest wszystko, co było na zajęciach, a nawet więcej :-)

Co warto sprawdzić:
- spróbuj usunąć tytuł strony ze spisu treści,
- może czytelniej będzie stronę zrobić w jednym języku - albo polską, albo angielską?
- przy równaniu wyróżniłabym legendę w taki sam sposób, jak wzór,
- zauważ, że emoji inaczej zachowuje się na podglądzie pliku w GitHubie, a inaczej na GitHub Pages :-) warto to skomentować!
- od punktu "Odsyłacze zewnętrzne (w komentarzu)" chyba jeszcze prace są w toku?

Co można wypróbować (częściowo spoza programu zajęć):
- obrazek z "dymkiem",
- wyróżnienie wzoru lub kawałka kodu wstawionego w tekst (nie w oddzielny blok).

**Comment by LeBerek** [comment]
Bardzo dziekuję,

@ "_od punktu "Odsyłacze zewnętrzne (w komentarzu)" chyba jeszcze prace są w toku?"

W nawiasach okrągłych chciałam umieścić komendy md.
Zapis (w komentarzu) odnosi się do komentarzy widocznych  w pliku md i niewidocznych na wyświetlanej stronie.  Tego zapisu używam tam gdzie wprowadzenie kilku znaków do okrąglych nawiasów uruchamia w VS Code "autokorektę" i zapis zostaje automatycznie zmieniony i skrócony.
Nie znalazłam jeszcze sposobu jak zatrzymać autokorektę. Może zapis  nawias -backslash - komenda-nawias by pozwolił zapisać komendę jako zwykły tekst bez znaczenia?

**Comment by LeBerek** [comment]
Sugerowane zmiany wprowadzone.
Gotowe do zamknięcia - jedna wątpliwość:
@ "wyróżnienie wzoru lub kawałka kodu wstawionego w tekst (nie w oddzielny blok)."
Czy Równanie nie spełnia kryterium wyróżnienia?

**Comment by martab0** [comment]
Wyróżnienie wzoru lub kawałka kodu wstawionego w tekst można zrobić tak:
```
💡 Encje `\&check;` i `\&cross;` w GHD na podglądzie poprawnie generują znaki.
Składnia: `\[text]\(url strony "opis linku")`
```
Efekt będzie taki (komentarze w GitHubie też renderują Markdown, więc od razu zobaczysz):
💡 Encje `\&check;` i `\&cross;` w GHD na podglądzie poprawnie generują znaki.
Składnia: `\[text]\(url strony "opis linku")`

Możesz przerobić przykłady składni na taki zapis zamiast kursywy.

**Comment by martab0** [comment]
Super eksperymenty z różnymi możliwościami Markdowna, gratulacje!!!
