### ISSUE TITLE
Nawiasy okrągłe i autokorekta w VS Code

### ISSUE THREAD

**Issue by martab0** [LeBerek/Markdown_vistula#4]
> W nawiasach okrągłych chciałam umieścić komendy md.
> Zapis (w komentarzu) odnosi się do komentarzy widocznych  w pliku md i niewidocznych na wyświetlanej stronie.  Tego zapisu używam tam gdzie wprowadzenie kilku znaków do okrąglych nawiasów uruchamia w VS Code "autokorektę" i zapis zostaje automatycznie zmieniony i skrócony.
> Nie znalazłam jeszcze sposobu jak zatrzymać autokorektę. Może zapis  nawias -backslash - komenda-nawias by pozwolił zapisać komendę jako zwykły tekst bez znaczenia?

Przyznam, że nie bardzo rozumiem, co się dzieje. Jeśli chcę wpisać w VS Code przykład kodu czy składni i nie chcę, żeby próbował mi w tym pomagać, to najczęściej ujmuję go w blok kodu albo ujmuję przykład w znaczki ` pozwalające wpisać kod w tekście, np. `tak wygląda kod w tekście`. 
Ale może źle zrozumiałam? Podaj przykład, postaram się to rozwikłać :)

**Comment by LeBerek** [comment]
To kwestia wypracowania dobrych praktyk :-)
Moja pomyłka, że przy pierwszych próbach w nagłówkach chciałam pisać wzory składni i jeszcze nie znałam funkcji backslashu.
W kolejnych próbach składnię usunęłam z nagłówków i przeniosłam do opisu.
Automatycznie skracanie składni w opisie  (np dla znaków `, ```, lub dla zapisu "[tekst]"  rozwiązałam stosowaniem znaku \.
Dziękuję za wsparcie.

**Comment by martab0** [comment]
Proszę bardzo :)
